// @codekit-prepend 'scripts/go_admin_page_admin_user.js'
// @codekit-prepend 'scripts/go_options.js'
// @codekit-prepend 'scripts/go_edit_store.js'
// @codekit-prepend 'scripts/buy_the_item.js'
// @codekit-prepend 'scripts/go_blogs.js'
// @codekit-prepend 'scripts/go_clipboard.js'
// @codekit-prepend 'scripts/go_tools.js'
// @codekit-prepend 'scripts/go_feedback.js'

// @codekit-prepend 'scripts/go_every_page.js'
// @codekit-prepend 'scripts/buy_the_item.js'
// @codekit-prepend 'scripts/go_fitvids.js'
// @codekit-prepend 'scripts/go_messages.js'
// @codekit-prepend 'scripts/go_videos_fit_and_box.js'
// @codekit-prepend 'scripts/go_map.js'